apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-demo
spec:
  hard:
    pods: "2"
---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: resourcequota
spec:
   replicas: 3
   selector: 
    matchLabels:
     kiran: kiran
   template:
     metadata:
       name: resq
       labels:
         kiran: kiran
     spec:
      containers:
        - name: main
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Kiran ; sleep 10; done"]

